spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Spring@MySQL22
    url: jdbc:mysql://localhost:3306/microservices
    
    jpa:
      show-sql: true
    